var Indicus_GENE_DNA = 'ACATTTGCTTCTGACACAACTGTGTTCACTAGCAACCTCAAACAGACACCATGGTGCATCTGACTCCTGAGGAGAAGTCTGCCGTTACTGCCCTGTGGGGCAAGGTGAACGTGGATGAAGTTGGTGGTGAGGCCCTGGGCAGGTTGGTATCAAGGTTACAAGACAGGTTTAAGGAGACCAATAGAAACTGGGCATGTGGAGACAGAGAAGACTCTTGGGTTTCTGATAGGCACTGACTCTCTCTGCCTATTGGTCTATTTTCCCACCCTTAGGCTGCTGGTGGTCTACCCTTGGACCCAGAGGTTCTTTGAGTCCTTTGGGGATCTGTCCACTCCTGATGCTGTTATGGGCAACCCTAAGGTGAAGGCTCATGGCAAGAAAGTGCTCGGTGCCTTTAGTGATGGCCTGGCTCACCTGGACAACCTCAAGGGCACCTTTGCCACACTGAGTGAGCTGCACTGTGACAAGCTGCACGTGGATCCTGAGAACTTCAGGGTGAGTCTATGGGACGCTTGATGTTTTCTTTCCCCTTCTTTTCTATGGTTAAGTTCATGTCATAGGAAGGGGATAAGTAACAGGGTACAGTTTAGAATGGGAAACAGACGAATGATTGCATCAGTGTGGAAGTCTCAGGATCGTTTTAGTTTCTTTTATTTGCTGTTCATAACAATTGTTTTCTTTTGTTTAATTCTTGCTTTCTTTTTTTTTCTTCTCCGCAATTTTTACTATTATACTTAATGCCTTAACATTGTGTATAACAAAAGGAAATATCTCTGAGATACATTAAGTAACTTAAAAAAAAACTTTACACAGTCTGCCTAGTACATTACTATTTGGAATATATGTGTGCTTATTTGCATATTCATAATCTCCCTACTTTATTTTCTTTTATTTTTAATTGATACATAATCATTATACATATTTATGGGTTAAAGTGTAATGTTTTAATATGTGTACACATATTGACCAAATCAGGGTAATTTTGCATTTGTAATTTTAAAAAATGCTTTCTTCTTTTAATATACTTTTTTGTTTATCTTATTTCTAATACTTTCCCTAATCTCTTTCTTTCAGGGCAATAATGATACAATGTATCATGCCTCTTTGCACCATTCTAAAGAATAACAGTGATAATTTCTGGGTTAAGGCAATAGCAATATCTCTGCATATAAATATTTCTGCATATAAATTGTAACTGATGTAAGAGGTTTCATATTGCTAATAGCAGCTACAATCCAGCTACCATTCTGCTTTTATTTTATGGTTGGGATAAGGCTGGATTATTCTGAGTCCAAGCTAGGCCCTTTTGCTAATCATGTTCATACCTCTTATCTTCCTCCCACAGCTCCTGGGCAACGTGCTGGTCTGTGTGCTGGCCCATCACTTTGGCAAAGAATTCACCCCACCAGTGCAGGCTGCCTATCAGAAAGTGGTGGCTGGTGTGGCTAATGCCCTGGCCCACAAGTATCACTAAGCTCGCTTTCTTGCTGTCCAATTTCTATTAAAGGTTCCTTTGTTCCCTAAGTCCAACTACTAAACTGGGGGATATTATGAAGGGCCTTGAGCATCTGGATTCTGCCTAATAAAAAACATTTATTTTCATTGC';
var startCodon = 'ATG';
var stopCodon = 'STOP';



var AMINO_ACIDS = {
  W: {key: 'W', name: 'Tryptophan'},
  C: {key: 'C', name: 'Cystine'},
  G: {key: 'G', name: 'Glycine'},
  R: {key: 'R', name: 'Arginine'},
  S: {key: 'S', name: 'Serine'},
  T: {key: 'T', name: 'Threonine'},
  A: {key: 'A', name: 'Alanine'},
  P: {key: 'P', name: 'Proline'},
  F: {key: 'F', name: 'Phenylalanine'},
  L: {key: 'L', name: 'Leucine'},
  V: {key: 'V', name: 'Valine'},
  I: {key: 'I', name: 'Isoleucine'},
  M: {key: 'M', name: 'Methionine'},
  Q: {key: 'Q', name: 'Glutamine'},
  H: {key: 'H', name: 'Histidine'},
  D: {key: 'D', name: 'Aspartic acid'},
  E: {key: 'E', name: 'Glutamic acid'},
  K: {key: 'K', name: 'Lysine'},
  N: {key: 'N', name: 'Asparagine'},
  Y: {key: 'Y', name: 'Tyrosine'},
};

var CODONS = {
  TTT: AMINO_ACIDS.F,
  TTC: AMINO_ACIDS.F,
  TTA: AMINO_ACIDS.L,
  TTG: AMINO_ACIDS.L,
  TCT: AMINO_ACIDS.S,
  TCC: AMINO_ACIDS.S,
  TCA: AMINO_ACIDS.S,
  TCG: AMINO_ACIDS.S,
  TAT: AMINO_ACIDS.Y,
  TAC: AMINO_ACIDS.Y,
  TAA: stopCodon,
  TAG: stopCodon,
  TGT: AMINO_ACIDS.C,
  TGC: AMINO_ACIDS.C,
  TGA: stopCodon,
  TGG: AMINO_ACIDS.W,
  CTT: AMINO_ACIDS.L,
  CTC: AMINO_ACIDS.L,
  CTA: AMINO_ACIDS.L,
  CTG: AMINO_ACIDS.L,
  CCT: AMINO_ACIDS.P,
  CCC: AMINO_ACIDS.P,
  CCA: AMINO_ACIDS.P,
  CCG: AMINO_ACIDS.P,
  CAT: AMINO_ACIDS.H,
  CAC: AMINO_ACIDS.H,
  CAA: AMINO_ACIDS.Q,
  CAG: AMINO_ACIDS.Q,
  CGT: AMINO_ACIDS.R,
  CGC: AMINO_ACIDS.R,
  CGA: AMINO_ACIDS.R,
  CGG: AMINO_ACIDS.R,
  ATT: AMINO_ACIDS.I,
  ATC: AMINO_ACIDS.I,
  ATA: AMINO_ACIDS.I,
  ATG: AMINO_ACIDS.M,
  ACT: AMINO_ACIDS.T,
  ACC: AMINO_ACIDS.T,
  ACA: AMINO_ACIDS.T,
  ACG: AMINO_ACIDS.T,
  AAT: AMINO_ACIDS.N,
  AAC: AMINO_ACIDS.N,
  AAA: AMINO_ACIDS.K,
  AAG: AMINO_ACIDS.K,
  AGT: AMINO_ACIDS.S,
  AGC: AMINO_ACIDS.S,
  AGA: AMINO_ACIDS.R,
  AGG: AMINO_ACIDS.R,
  GTT: AMINO_ACIDS.V,
  GTC: AMINO_ACIDS.V,
  GTA: AMINO_ACIDS.V,
  GTG: AMINO_ACIDS.V,
  GCT: AMINO_ACIDS.A,
  GCC: AMINO_ACIDS.A,
  GCA: AMINO_ACIDS.A,
  GCG: AMINO_ACIDS.A,
  GAT: AMINO_ACIDS.D,
  GAC: AMINO_ACIDS.D,
  GAA: AMINO_ACIDS.E,
  GAG: AMINO_ACIDS.E,
  GGT: AMINO_ACIDS.G,
  GGC: AMINO_ACIDS.G,
  GGA: AMINO_ACIDS.G,
  GGG: AMINO_ACIDS.G,
};

function translate(dna) {
  var result = [];
  var translating = false;

  for (var i = 0; i < dna.length; i += (translating ? 3 : 1)) {
    var codon = dna.slice(i, i + 3);

    if (!translating) {
      if (codon === startCodon) {
        translating = true;
      } else {
        continue;
      }
    }

    var aminoAcid = CODONS[codon];

    if (aminoAcid === stopCodon) {
      break;
    }

    result.push(aminoAcid.key);
  }

  return result.join('');
}

function expressGene(dna) {
  var protein = translate(dna);
  return protein;
}

var theProteinSequence = expressGene(Indicus_GENE_DNA);

document.getElementById('protein').textContent = theProteinSequence;
